#------------------------------------------------------------------------
#  Copyright 2008-2009 (c) Jeff Brown <spadix@users.sourceforge.net>
#
#  This file is part of the ZBar Bar Code Reader.
#
#  The ZBar Bar Code Reader is free software; you can redistribute it
#  and/or modify it under the terms of the GNU Lesser Public License as
#  published by the Free Software Foundation; either version 2.1 of
#  the License, or (at your option) any later version.
#
#  The ZBar Bar Code Reader is distributed in the hope that it will be
#  useful, but WITHOUT ANY WARRANTY; without even the implied warranty
#  of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Lesser Public License for more details.
#
#  You should have received a copy of the GNU Lesser Public License
#  along with the ZBar Bar Code Reader; if not, write to the Free
#  Software Foundation, Inc., 51 Franklin St, Fifth Floor,
#  Boston, MA  02110-1301  USA
#
#  http://sourceforge.net/projects/zbar
#------------------------------------------------------------------------

=pod

=head1 NAME

Barcode::ZBar::ImageScanner - scan images for bar codes

=head1 SYNOPSIS

    use Barcode::ZBar;
    
    my $scanner = Barcode::ZBar::ImageScanner->new();
    $scanner->parse_config('i25.disable');
    $scanner->scan_image($image);

=head1 DESCRIPTION

A Barcode::ZBar::ImageScanner is used to scan for bar codes in a
Barcode::ZBar::Image.

=head1 REFERENCE

=head2 Methods

=over 4

=item new()

Create a new bar code image scanner instance.

=item get_results()

Return a list of Barcode::ZBar::Symbol results from the last scanned
image.

=item scan_image([I<image>])

Scan a Barcode::ZBar::Image for bar codes.  The image must be in the
"Y800" format.  If necessary, use C<< I<$image>->convert("Y800") >> to
convert from other supported formats to Y800 before scanning.

=item enable_cache([I<enable>])

Enable the inter-image result consistency cache.

=item parse_config(I<configstr>)

Apply a decoder configuration setting.  See the documentation for
C<zbarcam>/C<zbarimg> for available configuration options.

=item recycle_image([I<image>])

Remove previously decoded results from a Barcode::ZBar::Image and
recycle the associated memory.

=back

=head1 SEE ALSO

Barcode::ZBar, Barcode::ZBar::Image, zbarimg(1), zbarcam(1)

http://zbar.sf.net

=head1 AUTHOR

Jeff Brown, E<lt>spadix@users.sourceforge.netE<gt>

=head1 COPYRIGHT AND LICENSE

Copyright 2008-2009 (c) Jeff Brown E<lt>spadix@users.sourceforge.netE<gt>

The ZBar Bar Code Reader is free software; you can redistribute it
and/or modify it under the terms of the GNU Lesser Public License as
published by the Free Software Foundation; either version 2.1 of
the License, or (at your option) any later version.

=cut
